<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <RootNamespace>WFL_Tool</RootNamespace>
    <StartupObject>WFL_Tool.My.MyApplication</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <Platforms>AnyCPU;x64</Platforms>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
    <ApplicationIcon>xinlogo.ico</ApplicationIcon>
    <AssemblyVersion>15.2.9472.5</AssemblyVersion>
    <FileVersion>15.2.9472.5</FileVersion>
    <Copyright>版权所有 © 2026 董博涛 保留所有权利.</Copyright>
    <Company>© 2026 董博涛</Company>
    <Product>电脑功能启动器 (x64)</Product>
    <Title>WFL Tool</Title>
    <AssemblyTitle>WFL Tool</AssemblyTitle>
    <Description>WFL Tool</Description>
    <Version>15.2.9472.5</Version>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <NeutralLanguage>zh-Hans-HK</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineDebug>True</DefineDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineDebug>True</DefineDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineDebug>False</DefineDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineDebug>False</DefineDebug>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xinlogo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Settings.settings">
      <CustomToolNamespace>My</CustomToolNamespace>
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

</Project>